version: "3.4"
services:
  mariadb:
    image: mariadb

    container_name: alura-mariadb
    
    ports:
      - 3306:3306

    restart: on-failure

    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: springboot3
      MYSQL_USER: henio
      MYSQL_PASSWORD: 123

    volumes:
      - alura:/var/lib/mysql

volumes:
  alura: